SUBROUTINE UPDATE(Q)
  USE LJNPTMOD
  USE LJNPTMC
  IMPLICIT NONE
  INTEGER :: I
  DOUBLE PRECISION :: ROEMAX,EFACT,Q(3,N_ATOM),EPRIME,ECR
   
  NTOTAL=NTOTAL+1

  IF(MOD(NTOTAL,UFREQ).EQ.0) THEN
     ECR=LJ12+LJ6-ENOT
     EAVE=EAVE + ECR
     EPRIME=LJ12*VFAC12 + LJ6*VFAC6 - ENOT
     EAVEFD=EAVEFD + EPRIME
     NUPDATES=NUPDATES+1
     ROEMAX=ZCURR(ARRYSIZE)   
     IF(NVT) THEN
        IF(MOD(NTOTAL,VSFREQ).EQ.0) CALL PRCALC(Q)
        PAVE=PAVE+PCURR
        DO I=1,ARRYSIZE
           EFACT=EXP(ZCURR(I)-ROEMAX)
           ZTOT(I)=ZTOT(I)+EFACT        
           VDATA(I)=VDATA(I)+ECR*EFACT               ! <E(T,V)> not <V>    
           EFACT=EXP(-BETA(I)*EPRIME-ROEMAX)
           ZTV2(I)=ZTV2(I)+EFACT
           EAVE2(I)=EAVE2(I)+EPRIME*EFACT 
        ENDDO
     ELSE
        DO I=1,ARRYSIZE
           EFACT=EXP(ZCURR(I)-ROEMAX)
           ZTOT(I)=ZTOT(I)+EFACT
           VDATA(I)=VDATA(I)+VCURR*EFACT  
        ENDDO
     ENDIF
  ENDIF
  
  IF((NUPDATES.GE.1).AND.(NUPDATES.EQ.WFREQ)) CALL WRTZ(Q)
  IF((NTOTAL.GT.NEQUIL).AND.(FFREQ.GT.0).AND.(MOD(NTOTAL,FFREQ).EQ.0)) CALL FRCOUT(Q)
     
END SUBROUTINE UPDATE

SUBROUTINE WRTZ(Q)
  USE LJNPTMOD
  USE LJNPTMC
  IMPLICIT NONE
  INTEGER :: I
  DOUBLE PRECISION :: Q(3,N_ATOM)
   
  BLCK=BLCK+1

  WRITE(FILEIND,"(A8,I8,I12)") "<BLOCK> ",BLCK,NUPDATES

  DO I=1,N_ATOM
     WRITE(QFILEIND,"(F9.5,A1,F9.5,A1,F9.5)") BL*Q(1,I)," ",BL*Q(2,I)," ",BL*Q(3,I)
  ENDDO

  CALL FLUSH(QFILEIND)

  REWIND(QFILEIND)

  WRITE(FILEIND,"(A8,I12)") "<NTOTAL> ",NTOTAL
  WRITE(FILEIND,"(A8,I12)") "<NTACCP> ",NTACCPT
  WRITE(FILEIND,"(A9,I12)") "<NTRANS> ",NTRANS
  WRITE(FILEIND,"(A14,F9.4)") "<ACCPTRATIO>  ", FLOAT(NTACCPT)/FLOAT(NTRANS)
  WRITE(FILEIND,"(A14,F7.4)") "<STEPLENGTH>  ",STPLEN
  WRITE(FILEIND,"(A10,F12.5)") "<BOXLXYZ> ", BL
  WRITE(FILEIND,"(A8,F12.5,2I12,F9.5)") "<VSTEP> ", VSLEN,NVACCT,NVSTEP,FLOAT(NVACCT)/FLOAT(NVSTEP)
  IF(NVT) THEN
     WRITE(FILEIND,"(A11,F22.5,I7)") "<PRESSURE> ", PAVE, N_ATOM
  ELSE
     WRITE(FILEIND,"(A11,F12.5,I7)") "<PRESSURE> ", PRESSURE(ARRYSIZE), N_ATOM
  ENDIF
  
  WRITE(FILEIND,"(A7,F12.5)") "<ENOT> ", ENOT    
  
  WRITE(FILEIND,"(A7,2F27.7,F15.7)") "<EAVE> ", EAVE,EAVEFD,VDIFF

  IF(mynode.EQ.0) THEN
     WRITE(FILEIND,"(A14,A4,F10.4)") "<PTACCPRATIO> "," -- ", FLOAT(NSWAPS(2))/FLOAT(NSWPATT(2))
  ELSE 
     IF(mynode.EQ.(NREPS-1)) THEN
        WRITE(FILEIND,"(A14,F10.4,A4)") "<PTACCPRATIO> ",FLOAT(NSWAPS(1))/FLOAT(NSWPATT(1)),"  --"
     ELSE
        WRITE(FILEIND,"(A14,F10.4,A1,F10.4)") "<PTACCPRATIO> ",FLOAT(NSWAPS(1))/FLOAT(NSWPATT(1))," ", FLOAT(NSWAPS(2))/FLOAT(NSWPATT(2))
     ENDIF
  ENDIF
  WRITE(FILEIND,"(A8,I8,A1,I8)") "<PTACC> ",NSWAPS(1)," ", NSWAPS(2)
  WRITE(FILEIND,"(A8,I8,A1,I8)") "<PTATT> ",NSWPATT(1)," ", NSWPATT(2)
  
  IF(PGRID) THEN
     DO I=1,ARRYSIZE
        WRITE(FILEIND,"(F21.16,A2,ES27.18E4,A2,ES27.18E4)") PRESSURE(I),"  ",ZTOT(I),"  ",VDATA(I)          
     ENDDO
  ELSE
     IF(NPT) THEN
        DO I=1,ARRYSIZE
           WRITE(FILEIND,"(F21.16,A2,ES27.18E4,A2,ES27.18E4)") BETA(I),"  ",ZTOT(I),"  ",VDATA(I)      
        ENDDO
     ELSE
        DO I=1,ARRYSIZE
           WRITE(FILEIND,"(F21.16,A1,ES27.18E4,A1,ES27.18E4,A1,ES27.18E4,A1,ES27.18E4)") BETA(I),"  ",ZTOT(I),"  ",VDATA(I)," ",ZTV2(I)," ",EAVE2(I)      
        ENDDO
     ENDIF
  ENDIF
  
  CALL FLUSH(FILEIND)

  NUPDATES=0
  ZTOT=0.0D0
  VDATA=0.0D0
  EAVE=0.0D0
  PAVE=0.0D0
  EAVEFD=0.0D0
  ZTV2=0.0D0
  EAVE2=0.0D0

END SUBROUTINE WRTZ

SUBROUTINE FRCOUT(Q)
  USE LJNPTMOD
  USE LJNPTMC
  IMPLICIT NONE
  INTEGER :: I
  DOUBLE PRECISION :: Q(3,N_ATOM), FRC(3,N_ATOM)

  CALL CALCFORCES(Q,FRC)

  DO I=1,N_ATOM
     WRITE(FRCFIND,"(F12.5)") (FRC(1,I)**2 + FRC(2,I)**2 + FRC(3,I)**2)**0.5D0
  ENDDO

  WRITE(FRCFIND,*)

  CALL FLUSH(FRCFIND)

END SUBROUTINE FRCOUT

SUBROUTINE VMDCOORDS(Q,TAG)
  USE LJNPTMOD
  USE LJNPTMC
  IMPLICIT NONE
  INTEGER :: I
  DOUBLE PRECISION :: Q(3,N_ATOM)
  CHARACTER*2 :: TAG

  WRITE(VFILEIND,"(I4)") N_ATOM
  WRITE(VFILEIND,"(A2,I9)") "# ",NTOTAL
  DO I=1,N_ATOM
     WRITE(VFILEIND,"(A2,A1,F12.5,A1,F12.5,A1,F12.5)") TAG," ",BL*Q(1,I)," ",BL*Q(2,I)," ",BL*Q(3,I)
  ENDDO

  CALL FLUSH(VFILEIND)

END SUBROUTINE VMDCOORDS
